---
title: "Salmon Escapements"
author: "Jim Magdanz"
date: "October 17, 2018"
output:
  html_document
    toc:yes
    number_sections:yes
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(leaflet) # maps
  library(ggplot2)
  library(tidyr)
  library(dplyr)
  library(DT)
})
```

## Daily Escapement Data

Daily escapements: [Alaska Department of Fish and Game. 2017. Daily salmon escapement counts from the OceanAK database, Alaska, 1921-2017. Knowledge Network for Biocomplexity. doi:10.5063/F1TX3CKH](http://doi:10.5063/F1TX3CKH)


```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = FALSE)

```

```{r}
esc_med <- esc %>%
  separate(sampleDate, c("Year", "Month", "Day"), "-", remove=F) %>% 
  group_by(Year, Species) %>% 
  summarise(AnnualCount = sum(DailyCount)) %>% 
  group_by(Year,Species) %>% 
  summarize(medianEscapement = median(AnnualCount))

```
## Bar Plot

```{r}

ggplot(esc_med, aes(x=Species, y=medianEscapement)) +
  geom_col() +
  coord_flip()

```

```{r}
locations <- esc %>% 
  select(Location, Latitude, Longitude) %>% 
  group_by(Location, Latitude, Longitude) %>% 
  summarize(n =n()) %>% 
  drop_na()

```


```{r}

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng=~Longitude, lat=~Latitude, popup=~Location)

```



